{
 "title": "Kubernetes / Compute Resources / GPU Status",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(node_cpu_seconds_total, cluster)"
   },
   {
    "name": "cluster",
    "query": "label_values(node_cpu_seconds_total, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(utilization_gpu{cluster=\"$cluster\"})/100"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "avg(temperature_gpu{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(temperature_gpu{cluster=\"$cluster\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "GPU memory utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(utilization_memory{cluster=\"$cluster\"})/100"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\"}[$__interval]))"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "GPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(utilization_gpu{cluster=\"$cluster\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(memory_used{cluster=\"$cluster\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "CPU Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(mixin_pod_workload{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "count(avg(mixin_pod_workload{cluster=\"$cluster\"}) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\"}) by (namespace) / sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\"}) by (namespace) / sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\"}) by (namespace)"
    }
   ]
  },
  { "title": "Memory Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Requests by Namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(mixin_pod_workload{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "count(avg(mixin_pod_workload{cluster=\"$cluster\"}) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!=\"\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\"}) by (namespace)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Average Container Bandwidth by Namespace: Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Average Container Bandwidth by Namespace: Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=~\".+\"}[$__interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Rate of Received Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=~\".+\"}[$__interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Rate of Transmitted Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=~\".+\"}[$__interval])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}